name: Publish on NPM

on:
  push:
    branches:
      - main
      - canary

permissions:
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      # Publish @seyuna/ui to npm
      - name: Publish @seyuna/ui
        run: |
          cd npm
          echo "Publishing @seyuna/ui..."

          if [ -f "package.json" ]; then
            NAME=$(node -p "require('./package.json').name")
            VERSION=$(node -p "require('./package.json').version")

            if npm show "$NAME@$VERSION" &>/dev/null; then
              echo "Version $VERSION of $NAME already exists, skipping..."
            else
              npm ci
              npm publish --provenance --access public
            fi
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
